baseline-forms-demo-build:
	./bin/pip install -e src/rex.instrument/demo
	./bin/pip install -e src/rex.forms/demo
	./bin/rex deploy rex.forms_demo
	./bin/yarn --cwd js/rex-forms-demo run build
	${RSH} ln -sf /app/js/rex-forms-demo/build share/rex/rex.forms_demo/www/bundle
.PHONY: baseline-forms-demo-build

baseline-forms-demo-start:
	./bin/honcho --procfile=src/rex.forms/demo/Procfile start
.PHONY: baseline-forms-demo-start

