#!/usr/bin/env python

# Runs `rex` script under coverage.

import sys
import os, os.path


# Chdir to `sandbox`.
os.chdir(os.path.join(os.path.dirname(__file__), '../sandbox'))

# Fix executable name.
sys.argv[0] = 'rex'

# Turn on coverage.
try:
    import coverage
except ImportError:
    coverage = None

if coverage is not None:
    C = coverage.coverage(
            data_file='./coverage.dat',
            branch=True,
            source=['rex.ctl'])
    C.load()
    C.start()

try:
    # Run the `rex` itself.
    from rex.ctl import main
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        pass

finally:
    # Save coverage data.
    if coverage is not None:
        C.stop()
        C.save()


