ln -s ../src/rex.action/doc/ rex.action
ln -s ../src/rex.core/doc/ rex.core
ln -s ../src/rex.ctl/doc/ rex.ctl
ln -s ../src/rex.db/doc/ rex.db
ln -s ../src/rex.deploy/doc/ rex.deploy
ln -s ../src/rex.expression/doc/ rex.expression
ln -s ../src/rex.forms/doc/ rex.forms
ln -s ../src/rex.i18n/doc/ rex.i18n
ln -s ../src/rex.instrument/doc/ rex.instrument
ln -s ../src/rex.port/doc/ rex.port
ln -s ../src/rex.restful/doc/ rex.restful
ln -s ../src/rex.setup/doc/ rex.setup
ln -s ../src/rex.urlmap/doc/ rex.urlmap
ln -s ../src/rex.web/doc/ rex.web
ln -s ../src/rex.widget/doc/ rex.widget
ln -s ../src/rex.widget_chrome/doc/ rex.widget_chrome
