from setuptools import setup, find_packages

setup(
    name='rexdb.platform',
    version='3.0.0.0',
    description='RexPlatform Capstone Project',
    long_description=open('README.rst', 'r').read(),
    maintainer='Prometheus Research, LLC',
    license='AGPLv3',
    url='https://bitbucket.org/rexdb/rexdb.platform',
    include_package_data=True,
    setup_requires=[
        'rex.setup == 1.2.2',
    ],
    install_requires=[ 
        'HTSQL==2.3.3.20141007',
        'HTSQL-PGSQL==2.3.3.20141007',
        'COGS==0.3.0',
        'rex.application==1.2.8',
        'rex.convert==3.0.2',
        'rex.core==1.6.2',
        'rex.ctl==1.4.1',
        'rex.db==2.1.0',
        'rex.deploy==1.5.0',
        'rex.entry==0.13.1',
#        'rex.explore==3.2.0',
#        'rex.explore_ui==5.0.0',
        'rex.expression==1.3.0',
        'rex.formbuilder==3.0.0',
        'rex.forms==0.25.1',
        'rex.htraf==1.0.10',
        'rex.i18n==0.3.0',
        'rex.instrument==0.11.2',
        'rex.port==0.1.0',
        'rex.restful==0.2.1',
        'rex.rdoma==0.17.0',
        'rex.sendmail==1.0.1',
        'rex.ui==2.1.4',
        'rex.urlmap==2.2.0',
        'rex.user_manager==0.0.12',
        'rex.vendor==2.0.0',
        'rex.web==2.2.3',
    ],
) 

