from setuptools import setup, find_packages

setup(
    name='rex.platform',
    version='4.0.0.0',
    description='RexDB Capstone Project',
    long_description=open('README.rst', 'r').read(),
    maintainer='Prometheus Research, LLC',
    license='AGPLv3',
    url='https://bitbucket.org/rexdb/rexdb.platform',
    include_package_data=True,
    setup_requires=[
        'rex.setup >= 2.0.0',
    ],
    install_requires=[ 
        'HTSQL==2.3.3.20150109',
        'HTSQL-PGSQL==2.3.3.20150109',
        'COGS==0.3.0',
        'rex.applet==0.0.1',
#        'rex.convert==3.0.8',
        'rex.core==1.10.0',
        'rex.ctl==1.7.0',
        'rex.db==3.0.0',
        'rex.deploy==2.0.0',
#        'rex.entry==0.14.0',
#        'rex.explore==3.2.0',
#        'rex.explore_ui==5.0.0',
        'rex.expression==1.4.0',
#        'rex.formbuilder==3.0.2',
#        'rex.forms==0.9.9',
#        'rex.i18n==0.3.0',
#        'rex.instrument==0.12.0',
        'rex.port==1.0.2',
#        'rex.restful==0.2.1',
#        'rex.sendmail==1.0.2',
        'rex.urlmap==2.6.0',
#        'rex.vendor==2.0.1',
        'rex.web==3.1.0',
        'rex.widget==0.2.9',
    ],
    rex_init='-',
)

