BIN = ./node_modules/.bin

test::
	@echo "This cannot be tested headless. Use 'test-watch' and attach browsers manually to the karma server."

test-watch::
	@$(BIN)/karma start

lint::
	@$(BIN)/eslint ./lib

