query User(
  $offset: Int
  $limit: Int
  $system_admin: Boolean
  $expired: Boolean
  $has_phone: Boolean
  $search: String
  $sort: sort_user_direction
) {
  user {
    paginated(
      offset: $offset
      limit: $limit
      system_admin: $system_admin
      expired: $expired
      has_phone: $has_phone
      search: $search
      sort: $sort
    ) {
      remote_user
      expires
      expired
      system_admin
      phone
      value
      id
    }
  }
}
