ln -s  ../../../rex.acquire_actions/js rex-acquire-actions 
ln -s  ../../../rex.action/js rex-action 
ln -s  ../../../rex.dbgui/js rex-dbgui 
ln -s  ../../../rex.expression/js rex-expression 
ln -s  ../../../rex.formbuilder/js rex-formbuilder 
ln -s  ../../../rex.forms/js rex-forms 
ln -s  ../../../rex.i18n/js rex-i18n 
ln -s  ../../../rex.mart_actions/js rex-mart-actions 
ln -s  ../../../rex.query/js rex-query 
ln -s  ../../../rex.widget/js rex-widget 
ln -s  ../../../rex.widget_chrome/js rex-widget-chrome 
